import { getTodayString, formatDateInput } from './utils.js';

export function getDefaultHistoryFromDate() {
    const today = new Date();
    today.setDate(today.getDate() - 3);
    return formatDateInput(today);
}

export const state = {
    foods: [],
    entries: [],
    selectedFoods: [],
    selectedDate: getTodayString(),
    filterFromDate: getDefaultHistoryFromDate(),
    filterToDate: getTodayString(),
    filterDate: '',
    searchCategory: 'all',
    onlyFreshGreen: false,
    filterCategory: 'all',
    filterStatus: 'all',
    historyMode: false,
    historyDeleteMode: false,
    isSearchOverlayOpen: false,
};

export const ui = {
    dateChipButton: document.getElementById('dateChipButton'),
    dateChipText: document.getElementById('dateChipText'),
    entryDate: document.getElementById('entryDate'),
    todayButton: document.getElementById('todayButton'),
    categoryChipButton: document.getElementById('categoryChipButton'),
    categoryChipText: document.getElementById('categoryChipText'),
    searchCategory: document.getElementById('searchCategory'),
    categoryClearButton: document.getElementById('categoryClearButton'),
    onlyFreshGreenFoods: document.getElementById('onlyFreshGreenFoods'),
    searchFilterBar: document.querySelector('.search-filter-bar'),
    searchField: document.getElementById('searchField'),
    foodSearchLabel: document.getElementById('foodSearchLabel'),
    searchCloseButton: document.getElementById('searchCloseButton'),
    searchClearButton: document.getElementById('searchClearButton'),
    searchDoneButton: document.getElementById('searchDoneButton'),
    overlaySelectedFoods: document.getElementById('overlaySelectedFoods'),
    foodSearch: document.getElementById('foodSearch'),
    suggestions: document.getElementById('suggestions'),
    selectedFoods: document.getElementById('selectedFoods'),
    saveButton: document.getElementById('saveButton'),
    historyList: document.getElementById('historyList'),
    historyFilters: document.getElementById('historyFilters'),
    historyModeToggle: document.getElementById('historyModeToggle'),
    filterFromDate: document.getElementById('filterFromDate'),
    filterToDate: document.getElementById('filterToDate'),
    filterCategory: document.getElementById('filterCategory'),
    historyCategoryChipButton: document.getElementById('historyCategoryChipButton'),
    historyCategoryChipText: document.getElementById('historyCategoryChipText'),
    historyCategoryClearButton: document.getElementById('historyCategoryClearButton'),
    filterStatus: document.getElementById('filterStatus'),
    historyStatusChipButton: document.getElementById('historyStatusChipButton'),
    historyStatusChipText: document.getElementById('historyStatusChipText'),
    historyStatusClearButton: document.getElementById('historyStatusClearButton'),
    historyDeleteToggle: document.getElementById('historyDeleteToggle'),
    themeToggle: document.getElementById('themeToggle'),
    settingsButton: document.getElementById('settingsButton'),
    settingsModal: document.getElementById('settingsModal'),
    settingsCloseButton: document.getElementById('settingsCloseButton'),
    storageStatus: document.getElementById('storageStatus'),
    installButton: document.getElementById('installButton'),
    exportJsonButton: document.getElementById('exportJsonButton'),
    importFile: document.getElementById('importFile'),
    appVersion: document.getElementById('appVersion'),
    importModal: document.getElementById('importModal'),
    importModalTitle: document.getElementById('importModalTitle'),
    importModalText: document.getElementById('importModalText'),
    importMergeButton: document.getElementById('importMergeButton'),
    importReplaceButton: document.getElementById('importReplaceButton'),
    importCancelButton: document.getElementById('importCancelButton'),
    confirmModal: document.getElementById('confirmModal'),
    confirmModalText: document.getElementById('confirmModalText'),
    confirmModalList: document.getElementById('confirmModalList'),
    confirmProceedButton: document.getElementById('confirmProceedButton'),
    confirmCancelButton: document.getElementById('confirmCancelButton'),
    categoryModal: document.getElementById('categoryModal'),
    categoryModalTitle: document.getElementById('categoryModalTitle'),
    categoryModalDescription: document.getElementById('categoryModalDescription'),
    categoryModalCloseButton: document.getElementById('categoryModalCloseButton'),
    categoryModalGrid: document.getElementById('categoryModalGrid'),
    firstRunNotice: document.getElementById('firstRunNotice'),
    noticeOpenManagerButton: document.getElementById('noticeOpenManagerButton'),
    noticeDismissButton: document.getElementById('noticeDismissButton'),
    openFoodManagerButton: document.getElementById('openFoodManagerButton'),
    foodCountBadge: document.getElementById('foodCountBadge'),
    exportTolerancesButton: document.getElementById('exportTolerancesButton'),
    importTolerancesFile: document.getElementById('importTolerancesFile'),
    resetTolerancesButton: document.getElementById('resetTolerancesButton'),
    foodManagerModal: document.getElementById('foodManagerModal'),
    foodManagerCloseButton: document.getElementById('foodManagerCloseButton'),
    foodManagerCount: document.getElementById('foodManagerCount'),
    foodManagerSearch: document.getElementById('foodManagerSearch'),
    foodManagerCategoryFilter: document.getElementById('foodManagerCategoryFilter'),
    foodManagerToleranceFilter: document.getElementById('foodManagerToleranceFilter'),
    foodManagerList: document.getElementById('foodManagerList'),
    openAddFoodBtn: document.getElementById('openAddFoodBtn'),
    foodFormContainer: document.getElementById('foodFormContainer'),
    foodFormTitle: document.getElementById('foodFormTitle'),
    foodFormName: document.getElementById('foodFormName'),
    foodFormCategory: document.getElementById('foodFormCategory'),
    foodCategoryDatalist: document.getElementById('foodCategoryDatalist'),
    foodFormOriginalName: document.getElementById('foodFormOriginalName'),
    foodFormSaveBtn: document.getElementById('foodFormSaveBtn'),
    foodFormCancelBtn: document.getElementById('foodFormCancelBtn'),
    foodFormCancelBtn2: document.getElementById('foodFormCancelBtn2'),
};

export function isMobileView() {
    return window.matchMedia('(max-width: 760px), (max-height: 500px)').matches;
}
